error: [2020-03-18 03:41:49] Error: Cannot return null for non-nullable field Query.getPost.,    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:560:13),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5),    at async Promise.all (index 0)
error: [2020-03-18 03:42:08] Error: Cannot return null for non-nullable field Query.getPost.,    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:560:13),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5),    at async Promise.all (index 0)
error: [2020-03-18 03:47:38] CastError: Cast to ObjectId failed for value "5e720d2a83abf215a38808b9a8b" at path "_id" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at ObjectId.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:2117:8),    at model.Query._wrappedThunk [as _findOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 03:49:00] CastError: Cast to ObjectId failed for value "5e720d2a83abf215a38808b9a8b" at path "_id" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at ObjectId.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:2117:8),    at model.Query._wrappedThunk [as _findOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 03:49:35] CastError: Cast to ObjectId failed for value "5e720d2a83abf215a38808b9a8b" at path "_id" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at ObjectId.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:2117:8),    at model.Query._wrappedThunk [as _findOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 03:51:21] CastError: Cast to ObjectId failed for value "5e720d2a83abf215a38808b9a8b" at path "_id" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at ObjectId.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:2117:8),    at model.Query._wrappedThunk [as _findOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 04:06:08] CastError: Cast to ObjectId failed for value "5e720d2a83abf215a38808b9a8b" at path "_id" for model "Post",    at new CastError (D:\Projects\task\node_modules\mongoose\lib\error\cast.js:39:11),    at ObjectId.cast (D:\Projects\task\node_modules\mongoose\lib\schema\objectid.js:269:11),    at ObjectId.SchemaType.applySetters (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1010:12),    at ObjectId.SchemaType._castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1424:15),    at ObjectId.SchemaType.castForQuery (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1414:15),    at ObjectId.SchemaType.castForQueryWrapper (D:\Projects\task\node_modules\mongoose\lib\schematype.js:1393:15),    at cast (D:\Projects\task\node_modules\mongoose\lib\cast.js:315:32),    at model.Query.Query.cast (D:\Projects\task\node_modules\mongoose\lib\query.js:4685:12),    at model.Query.Query._castConditions (D:\Projects\task\node_modules\mongoose\lib\query.js:1862:10),    at model.Query.<anonymous> (D:\Projects\task\node_modules\mongoose\lib\query.js:2117:8),    at model.Query._wrappedThunk [as _findOne] (D:\Projects\task\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8),    at D:\Projects\task\node_modules\kareem\index.js:369:33,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 06:58:25] GraphQLError: Field "uploads" of type "[File]" must have a selection of subfields. Did you mean "uploads { ... }"?,    at Object.Field (D:\Projects\task\node_modules\graphql\validation\rules\ScalarLeafs.js:45:31),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:324:29),    at Object.enter (D:\Projects\task\node_modules\graphql\language\visitor.js:375:25),    at visit (D:\Projects\task\node_modules\graphql\language\visitor.js:242:26),    at Object.validate (D:\Projects\task\node_modules\graphql\validation\validate.js:73:24),    at validate (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:443:22),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:252:32),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:30:35] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:48:23] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:49:12] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:50:11] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:52:11] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:55:01] GraphQLError: Variable "$image" of required type "Upload!" was not provided.,    at _loop (D:\Projects\task\node_modules\graphql\execution\values.js:92:17),    at coerceVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:119:16),    at getVariableValues (D:\Projects\task\node_modules\graphql\execution\values.js:48:19),    at buildExecutionContext (D:\Projects\task\node_modules\graphql\execution\execute.js:184:61),    at executeImpl (D:\Projects\task\node_modules\graphql\execution\execute.js:89:20),    at Object.execute (D:\Projects\task\node_modules\graphql\execution\execute.js:64:35),    at D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:481:30,    at Generator.next (<anonymous>),    at D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:8:71,    at new Promise (<anonymous>),    at __awaiter (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:4:12),    at execute (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:225:20),    at Object.<anonymous> (D:\Projects\task\node_modules\apollo-server-core\src\requestPipeline.ts:364:30),    at Generator.next (<anonymous>),    at fulfilled (D:\Projects\task\node_modules\apollo-server-core\dist\requestPipeline.js:5:58),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:55:43] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:42:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:57:09] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:43:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 07:58:09] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:43:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:02:25] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:43:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:03:46] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:43:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:17:38] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:49:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:18:31] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:49:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:22:24] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:51:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:28:11] ValidationError: Post validation failed: imageFileName: Path `imageFileName` is required.,    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at D:\Projects\task\node_modules\mongoose\lib\document.js:2374:17,    at D:\Projects\task\node_modules\mongoose\lib\schematype.js:1099:9,    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: [2020-03-18 08:29:19] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:30:57] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:31:00] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:31:33] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:33:12] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:33:12] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:33:22] Error: ‘Upload’ scalar serialization unsupported.,    at GraphQLScalarType.serialize (D:\Projects\task\node_modules\apollo-server-core\node_modules\graphql-upload\lib\GraphQLUpload.js:18:11),    at completeLeafValue (D:\Projects\task\node_modules\graphql\execution\execute.js:635:37),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:579:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at completeValueCatchingError (D:\Projects\task\node_modules\graphql\execution\execute.js:495:19),    at resolveField (D:\Projects\task\node_modules\graphql\execution\execute.js:435:10),    at executeFields (D:\Projects\task\node_modules\graphql\execution\execute.js:275:18),    at collectAndExecuteSubfields (D:\Projects\task\node_modules\graphql\execution\execute.js:713:10),    at completeObjectValue (D:\Projects\task\node_modules\graphql\execution\execute.js:703:10),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:591:12),    at completeValue (D:\Projects\task\node_modules\graphql\execution\execute.js:557:21),    at D:\Projects\task\node_modules\graphql\execution\execute.js:492:16,    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error: [2020-03-18 08:52:32] ValidationError: Post validation failed: imageFileName: Cast to String failed for value "Promise {,  {,    filename: 'welcome.jpg',,    mimetype: 'image/jpeg',,    encoding: '7bit',,    createReadStream: [Function: createReadStream],  },}" at path "imageFileName",    at new ValidationError (D:\Projects\task\node_modules\mongoose\lib\error\validation.js:31:11),    at model.Document.invalidate (D:\Projects\task\node_modules\mongoose\lib\document.js:2552:32),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:1233:12),    at model._handleIndex (D:\Projects\task\node_modules\mongoose\lib\document.js:971:14),    at model.$set (D:\Projects\task\node_modules\mongoose\lib\document.js:913:22),    at model.Document (D:\Projects\task\node_modules\mongoose\lib\document.js:135:12),    at model.Model (D:\Projects\task\node_modules\mongoose\lib\model.js:104:12),    at new model (D:\Projects\task\node_modules\mongoose\lib\model.js:4653:15),    at _callee3$ (D:\Projects\task\app/resolvers.js:52:27),    at tryCatch (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:45:40),    at Generator.invoke [as _invoke] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:274:22),    at Generator.prototype.<computed> [as next] (D:\Projects\task\node_modules\regenerator-runtime\runtime.js:97:21),    at asyncGeneratorStep (D:\Projects\task\app\resolvers.js:14:103),    at _next (D:\Projects\task\app\resolvers.js:16:194),    at processTicksAndRejections (internal/process/task_queues.js:93:5)
